//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int messageId { get; set; }
        public int senderId { get; set; }
        public int receiverId { get; set; }
        public string message1 { get; set; }
        public bool seen { get; set; }
        public System.DateTime sendDateTime { get; set; }
        public string sendReceive { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
